### ISSUE TITLE
Unable to mount /share

### ISSUE THREAD

**Issue by dcmartin** [hassio-addons/addon-ftp#1]
Utilization of option to provide access to share/ directory fails when specified in options

mount: mounting /share on /ftproot/users/eyespy/share failed: Permission denied

## Expected behavior

Expected to have /share mounted

## Actual behavior

Permission denied

## Steps to reproduce

Change default configuration of addon to indicate "share": true (default is false)

## Proposed changes

None

**Comment by frenck** [comment]
Just to be sure,

Are you running Hass.io on a Generic Linux?
Or is it running on a Pi with the Hass.io official image (ResinOS)?

**Comment by frenck** [comment]
I've found the issue and resolved it in the development version.
Will be fixed in the next release.

More technical details:
New AppArmor capabilities in the latest Hass.io Supervisor caused the blocking. Add-on configuration has been changed in order to fix that.
