### ISSUE TITLE
Change the time of the FTP Server

### ISSUE THREAD

**Issue by JimmyJones79** [hassio-addons/addon-ftp#12]
I am on the East coast of the US in the Easter Time Zone, my Raspberry Pi 3b+ is running the latest updated version of Hass.io (Home Assistant). 

For some reason the FTP plug in is showing file creation times as if it was Hawaiian time instead of East Coast time.  This is weird because Hassio and the Raspberry OS are showing the correct time.

## Expected behavior

Show the file creation time as Eastern Time

## Actual behavior

file creation time is the Hawaiian time zone

## Steps to reproduce

I have no idea, I just added the plug-in, configured it, everything works fine except the time stamp

## Proposed changes

maybe allow you to manually set your time zone like in Hassio in the configuration.yaml
homeassistant:
  time_zone: America/New_York

I would like to thank you for creating this FTP add-on, it works great I must be missing something.

**Comment by frenck** [comment]
The timezone is not handled by the add-on, but by Home Assistant. From an add-on perspective, there is nothing to do.

**Comment by JimmyJones79** [comment]
![Timezone](https://user-images.githubusercontent.com/43500955/74973742-fae8b580-53f1-11ea-8793-a5b3f7d8c7c8.JPG)
Please take a look here I took a screen shot, the time of my hassio, is 15:00 (3pm), while the Date Modified of the last created folder shows 10:00:00 AM

**Comment by frenck** [comment]
Thanks, however, add-on does not handle anything with timezone, it is passed in by the Home Assistant Supervisor.

So, not sure what you want me to do at this point, but you are in the wrong place for this.

**Comment by JimmyJones79** [comment]
No problem and thank you for the quick response, I will open the issue up on Hass
