### ISSUE TITLE
addon indicates update is available, but running latest version.

### ISSUE THREAD

**Issue by JAAlperin** [hassio-addons/addon-ftp#13]
from the addon log:

Add-on version: 3.3.1
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.

**Comment by frenck** [comment]
Will automatically be fixed on next update. Has been fixed in the upstream base add-on base image.

**Comment by JAAlperin** [comment]
Should have also included this from log:
System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
Home Assistant Core: 0.108.9
Home Assistant Supervisor: 219

**Comment by JAAlperin** [comment]
Thanks, Frank.
There are other addons showing the same error.  Does each one have to be fixed, or does the fix you mentioned cover them.  I also have some addons showing available updates that are not. and have never been installed.
