### ISSUE TITLE
Uploaded files lost on restart

### ISSUE THREAD

**Issue by lociii** [hassio-addons/addon-ftp#14]
# Problem/Motivation

All uploaded data lost on restart of the container/addon

## Expected behavior

Data is stored on a volume that is not wiped on restart

## Actual behavior

Data is stored in /ftproot/ which is part of the image and gets wiped on restart

## Steps to reproduce

Set all of addons, backup, config, share to false for [username]

1. Upload a file
2. Check if the file is stored in /ftproot/users/[username]
3. Restart the addon
4. Check that /ftproot/users/[username] is empty

## Proposed changes

Mount a volume to /ftproot/ or at least document this behavior

**Comment by frenck** [comment]
The FTP root is not persistent storage, which is correct. It exposes the folders that are persistent. For example, the `share` and `config` folders.

**Comment by lociii** [comment]
Alright. Unfortunately this is not at all transparent to the user nor is there any information about it as far as I can see. I've uploaded files to the ftproot which were gone after module restart.
So I'd like to prevent other users from the same fate.

My proposal:
1. Improve documentation
2. Add a file to the ftproot with some explanation and warning

Is this something you would accept PRs for?
