### ISSUE TITLE
Where are the files?

### ISSUE THREAD

**Issue by colethegamer123** [hassio-addons/addon-ftp#15]
# Problem/Motivation

> I uploaded a lot of files, but only shown up inside `/var/lib/docker/overlay2/20c9ed508ebe51e105164f3b3834488bfa6b4fe856a0252fa0ce51632099fbb0/merged/ftproot/users/ftpuser/`, there is no directory link between host and the docker?

## Expected behavior

> Should see the uploaded files inside a local host folder.

## Actual behavior

> Files cannot be touched, because only located inside the docker.

## Steps to reproduce

> Use the addon with any settings.

## Proposed changes

> add the -v /localdirectory/:/dockerdirectory/ to the docker container so we can reach our files.
> 

Sorry if I misunderstood this but I try to fix it since days, and nobody on the forums was able to help with this.

**Comment by frenck** [comment]
Only use the folders provides by Home Assistant `config`, `share`, `addon`, `ssl`, `backup`. Those are the only ones that persist and are shared across the system.

**Comment by colethegamer123** [comment]
Yes but its not working :( but as I see you already closed. I made a full search on my server and the only place where it found the file is inside docker nowhere else. tested 3 times with reinstall.
