### ISSUE TITLE
Uploading files inside the share or media folder instead of root folder

### ISSUE THREAD

**Issue by colethegamer123** [hassio-addons/addon-ftp#16]
# Problem/Motivation

> I want to upload Camera records automaticly with FTP, HomeAssistant can only see share media ssl or addon folder, but the FTP uploads to the root folder, what is unuseable to no files are uploaded.

## Expected behavior

> Should be able to select the default folder for FTP, so when I join to the FTP server I should be inside share folder for example instead of root. On any Camera there is no feature to select directory inside a Server.

## Actual behavior

> Downloading to / folder

## Steps to reproduce

> Upload anything

## Proposed changes

> DEFAULT_DIRECTORY selectable inside the config, you set it to the same folder where you give access to FTP user, for example 
> share folder. Hundreds of devices and softwares would work with FTP addon then, now a bit unusable for most of the stuffs.

Thank you very much,

**Comment by colethegamer123** [comment]
https://community.home-assistant.io/t/yi-home-1080p-camera-yihack-allwinner-firmware-ftp-upload/227822

**Comment by sinclairpaul** [comment]
Based on your forum post, I see you have this resolved, which is the client should determine the file path/name.
