### ISSUE TITLE
pasv_address will only resolve a numeric ip, not a hostname.

### ISSUE THREAD

**Issue by justcop** [hassio-addons/addon-ftp#17]
# Problem/Motivation

> When I access my FTP remotely I can only connect passively if I use a numeric ip, if I change to my duckdns hostname then it doesn't work

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> Connect remotely to the server and used the following config file

port: 21
data_port: 20
banner: Welcome to the Hass.io FTP service.
pasv: true
pasv_min_port: 30000
pasv_max_port: 30010
pasv_address: 1.1.1.80 *real ip redacted*
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
implicit_ssl: false
max_clients: 5
users:
  - username: justcop
    password: *redacted*
    allow_chmod: true
    allow_download: true
    allow_upload: true
    allow_dirlist: true
    addons: false
    backup: false
    config: true
    media: true
    share: true
    ssl: false

this work

but when I change to:

port: 21
data_port: 20
banner: Welcome to the Hass.io FTP service.
pasv: true
pasv_min_port: 30000
pasv_max_port: 30010
pasv_address: ***.duckdns.org
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
implicit_ssl: false
max_clients: 5
users:
  - username: justcop
    password: *redacted*
    allow_chmod: true
    allow_download: true
    allow_upload: true
    allow_dirlist: true
    addons: false
    backup: false
    config: true
    media: true
    share: true
    ssl: false

it does not work. I know that this hostname otherwise correctly resolves as I'm using this as the address of the FTP

## Proposed changes

vsftp settings suggest a PASV_ADDR_RESOLVE option. Can this be enabled?

**Comment by frenck** [comment]
I guess that it can be added, feel free to jump in! 👍

**Comment by justcop** [comment]
extremely new to github and hassio. Long time amateur linuxer but not confident at all.
I've suggested a change, which is hopefully the right one and doesn't break anything.
Be gentle
