### ISSUE TITLE
FTP server does not work.

### ISSUE THREAD

**Issue by gribouk** [hassio-addons/addon-ftp#18]
# Problem/Motivation
I've installed the FTP server. Did standard set up and launched it. But cannot get FTP access. Any idea why?
> (Why the issue was filed)
No FTP access while FTP server is running
## Expected behavior

> (What you expected to happen)
grant FTP access
## Actual behavior

> (What actually happened)
no ftp access
## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
There is nothing I can do with this issue.

You basically wrote: I doesn't work. Any idea?

Answer: No, I have no idea what you did. Feel free to write up an issue with the reproduction scenario or steps you did.

**Comment by gribouk** [comment]
1. Install the aplication.
2. Use the setup:
port: 21
data_port: 20
banner: Welcome to the Hass.io FTP service.
pasv: true
pasv_min_port: 30000
pasv_max_port: 30010
pasv_address: ''
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
implicit_ssl: false
max_clients: 5
users:
  - username: admin
    password: pass
    allow_chmod: true
    allow_download: true
    allow_upload: true
    allow_dirlist: true
    addons: false
    backup: true
    config: true
    media: true
    share: true
    ssl: false
3. Run the aplication
------------------
Result: no matter what client I use I cannot acces this IP via FTP - does not connect, rejected by server...

**Comment by frenck** [comment]
That works for me.

**Comment by gribouk** [comment]
Did I do anything wrong with setup?

**Comment by gribouk** [comment]
FileZilla returns: ECONNREFUSED

**Comment by frenck** [comment]
meant the add-on didn't start, maybe? Anything in the add-on logs? Anything in the supervisor logs?
Any more info in your FTP client logs? Are you using the right address to connect to? Does it work on the internal network directly using IP? Are your client setting matching your server settings? Is there a firewall blocking it? Are you using the right protocol?

**Comment by gribouk** [comment]
IP address correct - positive
Add on strted - positive, green light on.
Add-on log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: FTP
 A secure and fast FTP server for Home Assistant
-----------------------------------------------------------
 Add-on version: 3.4.0
 You are running the latest version of this add-on.
 System: HassOS 4.13  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 0.116.2
 Home Assistant Supervisor: 247
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] users.sh: executing... 
[23:08:47] WARNING: Password is in the Have I Been Pwned database!
[23:08:47] WARNING: Password appeared 12 times!
[23:08:47] FATAL: 
[23:08:47] FATAL: We are trying to help you to protect your system the
[23:08:47] FATAL: best we can. Therefore, this add-on checks your
[23:08:47] FATAL: configured password again the HaveIBeenPwned database.
[23:08:47] FATAL: 
[23:08:47] FATAL: Unfortunately, your configured password is considered
[23:08:47] FATAL: unsafe. We highly recommend you to pick a different one.
[23:08:47] FATAL: 
[23:08:47] FATAL: Please change the password in the 'users[0].password' option.
[23:08:47] FATAL: 
[23:08:47] FATAL: Check the add-on manual for more information.
[23:08:47] FATAL: 
[cont-init.d] users.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by gribouk** [comment]
O.K. I got that. I nade the pass more compicated and it did connect finally...
