### ISSUE TITLE
Connect to USB mounted Folder

### ISSUE THREAD

**Issue by Jogiarea** [hassio-addons/addon-ftp#182]
# Problem/Motivation

Attempts to access folders connected via USB via FTP

## Expected behavior

Connectoion to USB via FTP

## Actual behavior
Hello, I have SAMBA NAS running and can access my second hard disk and all USB sticks there cleanly

Unfortunately I cannot save via smb with a surveillance camera.

Now I have tried to access via the FTP addon. I can also access share and media, but not the mounted drives.

I would need help here on how to make the folders accessible via FTP
![Screenshot 2024-02-06 224201](https://github.com/hassio-addons/addon-ftp/assets/86875561/0c03f188-1123-4f0f-a6d8-5a59883e6d13)
![Screenshot 2024-02-06 224045](https://github.com/hassio-addons/addon-ftp/assets/86875561/cb58afd5-9d8c-4345-b663-97b255a2a205)

**Comment by sinclairpaul** [comment]
It isn't supported by the addon.
