### ISSUE TITLE
Too many sessions - Connection refused

### ISSUE THREAD

**Issue by mkornmue** [hassio-addons/addon-ftp#200]
I tried multiple times with filezilla to connect to ftp but it refuses the connection constantly.
I can connect once and after five seconds i get a disconnect answer from 421.

It is possible to show the folders after the first connection. But i am not able to download the data i need because of this refused connection.

The protocol in FTP shows the following:
![image](https://github.com/user-attachments/assets/165ea5b3-2bef-437a-8066-7c767c6210c9)

Can someone help with that?

**Comment by TomHom91** [comment]
Can confirm I have the same issue. But I'n not 100% sure if it's a fault of this add-on, or that it is a problem within HA(OS).
I'm running OS Version 13.0 and Home Assistant Core 2024.8.2. 
When I want to upload with either FileZilla or WinSCP I get the same as @mkornmue.
But uploading within the Media section of Home Assistant Core also doesn't work. And when I try uploading via the terminal with the "scp" command, using the "Terminal & SSH" add-on it also doesn't want to upload.
@frenck perhaps beter to make a bug report in the Home Assistant GitHub page?

**Comment by sinclairpaul** [comment]
Assuming the default addon config, is the client configured for Passive mode?

**Comment by TomHom91** [comment]
Well, it fixed it self after de HAOS 13.1 update. Not sure way ...
