### ISSUE TITLE
!secret not working

### ISSUE THREAD

**Issue by Vout** [hassio-addons/addon-ftp#4]
# Problem/Motivation
For security reasons I would like to save my passwords in the ```secrets.yaml``` file. As stated in the documentation that should be possible however i'm receiving a error when saving the settings of the FTP addon.

## Expected behavior
To save my passwords in the ```secrets.yaml``` file and to use these in the FTP addon

## Actual behavior
FTP addon throughs out a error when saving the settings when using !secret ftp_username and !secret ftp_password

## Steps to reproduce
Use the following settings in the FTP addon,

```
{
      "username": "!secret ftp_username",
      "password": "!secret ftp_password",
      "allow_chmod": false,
      "allow_download": false,
      "allow_upload": true,
      "allow_dirlist": true,
      "addons": false,
      "backup": false,
      "config": true,
      "share": false,
      "ssl": false
    }
```

When using above settings i'm getting the following error,

```
not a valid value for dictionary value @ data['options']. Got {'log_level': 'info', 'port': 21, 'data_port': 20, 'banner': 'Dahua ip camera uploads', 'pasv': True, 'pasv_min_port': 30000, 'pasv_max_port': 30010, 'pasv_address': '', 'ssl': False, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem', 'implicit_ssl': False, 'max_clients': 5, 'users': [{'username': '!secret ftp_username', 'password': '!secret ftp_username', 'allow_chmod': False, 'allow_download': False, 'allow_upload': True, 'allow_dirlist': True, 'addons': False, 'backup': False, 'config'...
```

**Comment by tjorim** [comment]
Hi, could you please post your full add-on config here?

**Comment by Vout** [comment]
`{
  "log_level": "info",
  "port": 21,
  "data_port": 20,
  "banner": "IP camera uploads",
  "pasv": true,
  "pasv_min_port": 30000,
  "pasv_max_port": 30010,
  "pasv_address": "",
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "implicit_ssl": false,
  "max_clients": 5,
  "users": [
    {
      "username": "!secret dahua_username",
      "password": "!secret dahua_password",
      "allow_chmod": false,
      "allow_download": false,
      "allow_upload": true,
      "allow_dirlist": true,
      "addons": false,
      "backup": false,
      "config": true,
      "share": false,
      "ssl": false
    },
    {
      "username": "!secret escam_username",
      "password": "!secret escam_password",
      "allow_chmod": false,
      "allow_download": false,
      "allow_upload": true,
      "allow_dirlist": true,
      "addons": false,
      "backup": false,
      "config": true,
      "share": false,
      "ssl": false
    }
  ]
}`

Running the latest version of Hass.io and the FTP addon.

**Comment by tjorim** [comment]
Ok, think I found the cullprit, will try something out.

**Comment by geertmeersman** [comment]
@Vout how are you accessing the uploaded images from your dahua camera in hassio?
In my config I am unable to specify the folder, meaning that he uploads the images in the user folder, which is of course not shared. If you are using hassbian I will ask @tjorim to have the possibility to example chroot the user into the /config/www/ftp/username folder or sth like this

**Comment by Vout** [comment]
@geertmeersman i saved the in config/www/dahua but i'm working on an better solution now. I currently have this script running (https://github.com/Vout/dahua-mqtt). It checks the camera for IVS events and if triggered sends out an MQTT message that is used in Hass.io to trigger the snapshot service that is already available inside hass.io (https://www.home-assistant.io/components/camera/#service-snapshot)

I will update and include some documentation for it after the holidays.

**Comment by frenck** [comment]
@geertmeersman @Vout I would really appreciate if you'd didn't marched in onto a random issue with non-related questions to the issue.

If you are in need for support, please join our Discord server, try the community forums, or, if you are convinced it is an issue with the add-on, create a new issue on GitHub.

Thanks in advance. 👍
