### ISSUE TITLE
Feature Request: Add HA action/event after a file got uploaded

### ISSUE THREAD

**Issue by robertpenz** [hassio-addons/addon-ftp#61]
My IPCAM uploads video files and this would allow me to convert them with ffmpeg to a format that the media browser in HA allows viewing. It would also allow users with IPCAMs that don't support ONVIF to get an event if something moved in the cam view, for other uses.

As a bonus it would be nice if the file extension which lead to an event/action can be configured.

**Comment by frenck** [comment]
That is not a goal for an FTP server. And This won't be added.
Additionally, this is an issue tracker, not a feature request tracker.

You could try:

<https://www.home-assistant.io/integrations/folder_watcher/>

../Frenck
