### ISSUE TITLE
FTP Cannot Connect

### ISSUE THREAD

**Issue by jjanderson** [hassio-addons/addon-ftp#7]
# Problem/Motivation

> Cannot connect to FTP via WIN SCP or Filezilla

## Expected behavior

> Expect to connect and see files

## Actual behavior

> It will connect, but then I get the following error:

WIN SCP
SSL3 alert write: fatal: protocol version wrong version number Disconnected from server Could not retrieve directory listing Error listing directory '/'.

FileZilla:
Error:	GnuTLS error -15: An unexpected TLS packet was received.
Error:	Disconnected from server: ECONNABORTED - Connection aborted
Error:	Failed to retrieve directory listing

## Steps to reproduce

The following is my config in the component:

```
{
  "log_level": "info",
  "port": 21,
  "data_port": 20,
  "banner": "Welcome to the Hass.io FTP service.",
  "pasv": true,
  "pasv_min_port": 30000,
  "pasv_max_port": 30010,
  "pasv_address": "REDACTED.duckdns.org",
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "implicit_ssl": false,
  "max_clients": 5,
  "users": [
    {
      "username": "REDATED",
      "password": "REDATED",
      "allow_chmod": false,
      "allow_download": true,
      "allow_upload": true,
      "allow_dirlist": true,
      "addons": true,
      "backup": true,
      "config": true,
      "share": true,
      "ssl": false
    }
  ]
}
```
I have SSL through the duckdns component with Lets Encrypt
## Proposed changes

Possibly my config on RPI is wrong or client config wrong?

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

FROM THIS SITE: https://developer.ibm.com/answers/questions/213452/why-is-our-filezilla-ftp-client-receiving-gnutls-e/

In this situation it was found that the FTP server was configured (defaulted) to the draft level of the FTP/TLS RFCs. One effect of this is that the session is simply closed instead of first sending an SSL Close Alert message first.

If your TLSRFCLEVEL is configured as DRAFT, change it to TLSRFCLEVEL RFC4217. If it defaulted to DRAFT, add a TLSRFCLEVEL RFC4217 statement to the server's FTP.DATA input to change this behavior.

Specification of the TLSRFCLEVEL does not affect the initial SSL handshake or encryption of traffic; it changes the behavior when a session (or at least, SSL) ends. Specifically, configuring TLSRFCLEVEL RFC4217 will cause an SSL Close alert packet to be sent before actually closing the TCP connection (sending the FIN). Apparently the GnuTLS code used by FileZilla is strictly enforcing receipt of the alert, and errors out when a FIN arrives without the alert. So adding that configuration statement should resolve the problem with FileZilla not getting the LIST output.

<blockquote><img src="https://pbs.twimg.com/profile_images/576466300500779008/egJLokz-_400x400.jpeg" width="48" align="right"><div><strong><a href="https://developer.ibm.com/answers/questions/213452/why-is-our-filezilla-ftp-client-receiving-gnutls-e/">Why is our Filezilla FTP client receiving GnuTLS error -110 when listing directory on z/OS FTP server?</a></strong></div><div>We have FTPS configured on port 21 (security ALLOWED) and on port 990 (Security REQUIRED/Implicit).  Filezilla connects successfully to the z/OS FTP server by using TLS to secure the control connection.  But Filezilla cannot list the contents of a directory by using a TLS protected data connection. 
 The screen shot shows these Filezilla client messages:  
     Response:   125 List started OK 
   Error:      GnuTLS error -110 in gnu_tls_record_recv: The TLS 
               Connection was non-properly terminated. 
   Status:     Server did not properly shut down TLS connection 
   Error:      Could not read from transfer socket: ECONNABORTED - 
               Connection aborted 
   Response:   250 List completed successfully. 
   Error:      Failed to retrieve directory listing 

  
 We verified that there is no firewall between the client and the mainframe.  We also verified that the customer can connect to port 21 in the clear but receives an error on the same client if they try to use SSL/TLS (active FTP).</div></blockquote>

**Comment by frenck** [comment]
Moved this issue, since you created an issue in the wrong location.
Please consult the documentation on how to gain support the next time. Thanks 👍

**Comment by jjanderson** [comment]
Sorry.. my bad... let me know if you need any help with testing or anything, thanks

**Comment by frenck** [comment]
This depends on the implicit_ssl setting...
