### ISSUE TITLE
Inflexible FTP-client only stores files in ftp-add-on root directory --> root directory of ftp add on not available in home assistant

### ISSUE THREAD

**Issue by je-mei** [hassio-addons/addon-ftp#70]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
empty issue.

**Comment by je-mei** [comment]
empty issue enriched by data.

**Comment by frenck** [comment]
```
It would be great if you could set one home assistant folder, for example "share" as the ftp-add on root folder via configuration. That would be great.
```

That is not possible, as there are multiple folder involved. Sounds like this is not an add-on you can use. sorry.

**Comment by je-mei** [comment]
hi frecnk, what about my second proposal, to move all data - stored in the root - to one official via configuration item? regardless, the add-on is a great feature. thank you for your various developments.
Kind regards Jens

**Comment by frenck** [comment]
Sorry, that won't happen.
As said, this add-on is not suited for your use case.

**Comment by je-mei** [comment]
ok thank you and bye
