### ISSUE TITLE
FTP addon v4.2.0: TLS/SSL no longer working?

### ISSUE THREAD

**Issue by taufikp** [hassio-addons/addon-ftp#73]
Got this message when logging in to FTP server:
500 OOPS: error:141FC0B5:SSL routines:tls_setup_handshake:no ciphers available.

This didn't happen in the previous version. 

This is my current FTP addon and HA:
 Add-on version: 4.2.0
 You are running the latest version of this add-on.
 System: Ubuntu 20.04.2 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.6
 Home Assistant Supervisor: 2021.06.6

Setting SSL to 'false' in the configuration "solves" this issue, but of course this is not the solution.

Am I missing something?

**Comment by sinclairpaul** [comment]
Which client are you using?

**Comment by taufikp** [comment]
> Which client are you using?

Hi, I'm using FileZilla 3.52

**Comment by nhorvath** [comment]
Using curl or winscp (with ftps) i also can't connect since june 20th. I get a ssl handshake error with implicit_ssl: false (which is what I previously used). If I enable implicit ssl then I get the OOPS the @taufikp described.

**Comment by nhorvath** [comment]
This issue still occurs.

**Comment by taufikp** [comment]
It seems the new version, 4.2.1, has no fix for this issue.

**Comment by nhorvath** [comment]
Still broken
