### ISSUE TITLE
Pull request to add some documentation 

### ISSUE THREAD

**Issue by chrisn-au** [hassio-addons/addon-ftp#9]
# Problem/Motivation

To the untrained eye, it is not clear how to gain file system access to files that have been added to this  ftp server. This can be solved via some documentation updates  

## Expected behaviour

A section in the README.md file outlining that files can be accessed by by enabling the share,config or backup folder options

## Actual behaviour

The section does not exist

## Steps to reproduce

Read the README.md file

## Proposed changes

I will create a pull request to update the README.md file with changes that document this capability

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/64119114-5e761c80-cd99-11e9-8219-172b8b35affd.png)

note sure how to make that any clearer, each is listed.
Feel free to make an actual pull request (instead of an issue and title it pull request) to improve it.
